product/urls.py
from django.urls import path

from product.views import (
    HomeView,
    ProductDetailView,
    ResultListView,
    SubstituteListView,
)

app_name = "product"
urlpatterns = [
    path('', HomeView.as_view(),
         name="home"),

    path('<int:id>/', ProductDetailView.as_view(),
         name="product"),

    path('result/', ResultListView.as_view(),
         name="result"),

    path('<int:id>/substitute', SubstituteListView.as_view(),
         name="substitutes"),
]

user/urls.py
from django.urls import path

from user.views import (
    RegisterCreateView,
    PasswordsChangeView,
    SavedListView,
    SaveCreateView,
    AccountUpdateView,
    LegalView,
)

app_name = "account"
urlpatterns = [
    path('register/', RegisterCreateView.as_view(), name="register"),
    path('save/', SaveCreateView.as_view(), name="save"),
    path('myproduct/', SavedListView.as_view(), name="myproduct"),
    path('myaccount/', AccountUpdateView.as_view(), name="myaccount"),
    path('password/', PasswordsChangeView.as_view(), name="password_change"),
    path('legal/', LegalView.as_view(), name="legal"),
]

product/models.py
from django.shortcuts import reverse
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)


class Label(models.Model):
    name = models.CharField(max_length=200)


class Origin(models.Model):
    name = models.CharField(max_length=200)


class Store(models.Model):
    name = models.CharField(max_length=200)


class Product(models.Model):
    name = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    nova = models.IntegerField()
    nutri_score = models.CharField(max_length=1)
    label_score = models.IntegerField(default=0)

    salt = models.CharField(max_length=500)
    sugars = models.CharField(max_length=500)
    saturated = models.CharField(max_length=500)
    fat = models.CharField(max_length=500)

    url = models.CharField(max_length=500)
    image_url = models.CharField(max_length=500)
    categories = models.ManyToManyField(Category, related_name='products',
                                        blank=True)
    labels = models.ManyToManyField(Label, related_name='products', blank=True)
    origins = models.ManyToManyField(Origin, related_name='products',
                                     blank=True)
    stores = models.ManyToManyField(Store, related_name='products', blank=True)

    def get_absolute_url(self):
        return reverse("product:product", kwargs={"id": self.id})

    def get_substitute_url(self):
        return reverse("product:substitutes", kwargs={"id": self.id})

product/forms.py
from django import forms


class SearchBarForm(forms.Form):
    name = forms.CharField(
        label="",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "col-lg-8 col-md-8"
            }
        )
    )

product/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import (
    DetailView,
    ListView,
)

from product.forms import SearchBarForm
from product.models import Product
from product.queryset import get_substitute


class HomeView(View):
    # view for home
    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        form = SearchBarForm()
        context = {"form": form}
        return render(request, self.template_name, context)


class ProductDetailView(DetailView):
    # view for product
    template_name = "detail.html"

    def get_object(self, *args, **kwargs):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Product, id=id_)


class ResultListView(ListView):
    # view for result
    template_name = "result.html"

    def get_queryset(self):
        form = SearchBarForm(self.request.GET)
        user_input = form.data["name"]
        return Product.objects.filter(name__icontains=user_input)


class SubstituteListView(ListView):
    # view for substitutes
    template_name = "substitute.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['origin_product'] =\
            Product.objects.get(id=self.kwargs.get("id"))
        return context

    def get_queryset(self):
        user = self.request.user
        id_ = self.kwargs.get("id")

        queryset = get_substitute(id_, user)

        return queryset

product/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Touver des substitues à vaux produits de tous les jours" />
        <meta name="author" content="Rivolet Thibaut" />
        <title>Pur Beurre</title>
        <!-- Favicon-->
        <link rel="icon" type="image/svg+xml" href="../static/img/Logo.svg" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />

        {% load static %}

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/my.css' %}" rel="stylesheet" />
    </head>

    <body id="page-top">

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">

            <div class="container">
                <img type="image/svg+xml" src="{% static 'img/Logo.svg' %}" alt="Pur Beurre" width=3%>
                <a class="navbar-brand js-scroll-trigger" href="{% url 'product:home' %}">Pur Beurre</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto row">
                        <li class="nav-item col-lg-8 col-md-8">
                            <form  id="search_bar" action="{% url 'product:result' %}" method="GET">{% csrf_token %}
                            <input type="text" name="name" value="" id="name_bar"></form>
                        </li>
                        <li class="nav-item col-lg-1 col-md-1"><a href="{% url 'account:myaccount' %}"><i class="fas fa-user my-6"></i></a></li>
                        <li class="nav-item col-lg-1 col-md-1"><a href="{% url 'account:myproduct' %}"><img type="image/svg+xml" src="{% static 'img/icon.svg' %}" alt="carrot" width=10px ></a></li>
                        <li class="nav-item col-lg-1 col-md-1"><a href="/logout"><i class="fas fa-sign-out-alt"></i></a></li>
                    </ul>
                </div>
            </div>

        </nav>

        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container justify-content-center">
                <div class="row small text-center text-muted justify-content-center">
                    <a class="col-2" href="{% url 'product:home' %}#contact" >Contact</a>
                    <a class="col-2" href="{% url 'account:legal' %}">Mentions légales</a>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

product/templates/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    .bg-origin-product {
        background-image: linear-gradient(to bottom, rgba(92, 77, 66, 0.8) 0%, rgba(92, 77, 66, 0.8) 100%), url('{{ object.image_url }}');
        background-repeat: no-repeat;
        background-size: contain;
        background-position: center;
        background-color: black;
        color: white;
        padding: 5rem;
    }
</style>

<section class="page-section" id="detail">
    <div class="h-50 align-items-center justify-content-center text-center">
        <div class="justify-content-center text-center bg-origin-product" >
            <div class="row justify-content-center py-xl-5">
                <div class="col-lg-8 text-center">
                    <h3>{{ object.name }}</h3>
                </div>
            </div>
        </div>
        <div class="row no-gutters my-5">
            <div class="col-lg-6 col-sm-12 text-center">
                <p>Nuriscore</p>
                {% if object.nutri_score == "a" %}
                    {% load static %}
                    <img type="image/svg+xml" src="{% static 'img/nutriscore-a.svg' %}">
                {% elif object.nutri_score == "b" %}
                    <img type="image/svg+xml" src="{% static 'img/nutriscore-b.svg' %}">
                {% elif object.nutri_score == "c" %}
                    <img type="image/svg+xml" src="{% static 'img/nutriscore-c.svg' %}">
                {% elif object.nutri_score == "d" %}
                    <img type="image/svg+xml" src="{% static 'img/nutriscore-d.svg' %}">
                {% elif object.nutri_score == "e" %}
                    <img type="image/svg+xml" src="{% static 'img/nutriscore-e.svg' %}">
                {% else %}
                    <img type="image/svg+xml" src="{% static 'img/nutriscore.svg' %}">
                {% endif %}
            </div>
            <div class="col-lg-6 col-sm-12 text-center">
                <p>Repères nutritionnels (100g)</p>
                <p>Salt {{ object.salt }}</p>
                <p>sugars {{ object.sugars }}</p>
                <p>saturated-fat {{ object.saturated }}</p>
                <p>fat {{ object.fat }}</p>
            </div>
        </div>
        <div class="justify-content-center text-center ">
            <a href="{{ object.url }}">
                <button class="btn btn-primary">
                    voir la fiche d'openFoodFact
                </button>
            </a>
        </div>
    </div>
</section>
{% endblock %}

product/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-12 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
                <form  id="search" class="row"  action="{% url 'product:result' %}" method="GET">
                    {{ form }}
                    <button class="btn btn-primary col-lg-4 col-md-4" type="submit">Chercher</button>
                </form>
            </div>
        </div>
    </div>
</header>

<!-- AboutUs-->
<section class="page-section" id="aboutus">

        <div class="container container-fluid p-0">
            <div class="row justify-content-center text-center">
                <div class="col-lg-8 text-center">
                    <h2>Colette et Remy</h2>
                    <hr class="divider my-4 " />
                    <p class="text-muted mb-5">Notre restaurant, situé à Montmartre (Paris), compte une cinquantaine de couverts et ne désemplit pas. Notre spécialité, la ratatouille, nous attire une clientèle internationale charmée par les délices de ce plat typique.
                    Remy et Colette sont amoureux de la gastronomie française (on ne peut les blâmer !). Travaillant quotidiennement avec les meilleurs produits du terroir, ils affectionnent particulièrement la bonne chaire et aiment partager leur passion. Il est donc normal que Remy ait sauté au plafond quand Colette, un jour de déprime, sortit du placard un kilo de Nutella et l’attaqua à la petite cuillère. Pourquoi ne pas opter pour une pâte à tartiner aux noisettes, plus consistante et moins sucrée ? Pourquoi, oh pourquoi s’infliger une telle souffrance ? Rémy était sidéré. La réponse de Colette fut simple : elle n’avait pas trouvé de substitut assez convainquant. A vrai dire, elle n’avait même pas cherché.
                    Tous deux se souvinrent alors que nombre de leurs clients leur avaient compté, entre deux verres, qu’il était difficile de trouver des substituts aux cochonneries que nous mangions dès le petit déjeuner. Pourquoi ne pas lancer une plateforme web en ce sens ? Voici votre mission !
                    </p>
                </div>
            </div>
            <div class="row no-gutters ">
                <div class="col-lg-6 col-sm-12 text-center">
                    <img class="img-fluid" src="{% static 'img/face.png' %}" alt="" />
                    <p>Colette</p>
                </div>
                <div class="col-lg-6 col-sm-12 text-center">
                    <img class="img-fluid" src="{% static 'img/face.png' %}" alt="" />
                    <p>Remy</p>
                </div>
            </div>
        </div>

</section>

<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contactez-nous !</h2>
                <hr class="divider my-4" />
                <p class="text-muted mb-5">Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div>+1 (555) 123-4567</div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                <a class="d-block" href="mailto:contact@yourwebsite.com">contact@yourwebsite.com</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

product/templates/result.html
{% extends 'base.html' %}

{% block content %}
<section class="page-section" id="result">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h3>Résultats</h3>
                <hr class="divider my-4" />
            </div>
        </div>
        <div class="row">
            {% for instance in object_list %}
            <div class="align-content-center text-center col-lg-4 col-sm-12 my-col">
                    <a class="align-content-center text-center my-col" href="{{ instance.get_substitute_url }}">
                        <img class="product-img" src="{{ instance.image_url }}">
                        <p>{{ instance.name }}</p>
                    </a>
                    <a class="" href="{{ instance.get_absolute_url }}">detail</a>
                </p>
            </div>

            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

product/templates/substitute.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<style>
    .bg-origin-product {
        background-image: linear-gradient(to bottom, rgba(92, 77, 66, 0.8) 0%, rgba(92, 77, 66, 0.8) 100%), url('{{ origin_product.image_url }}');
        background-repeat: no-repeat;
        background-size: contain;
        background-position: center;
        background-color: black;
        color: white;
        padding: 5rem;
    }
</style>

<section class="page-section" id="result">
    <div class="container">
        <div class="justify-content-center text-center bg-origin-product" >
            <div class="row justify-content-center py-xl-5">
                <div class="col-lg-8 text-center">
                    <h3>{{ origin_product.name }}</h3>
                </div>
            </div>
        </div>
        <div class="row justify-content-center text-center">
            <div class="col-lg-8 text-center">
                <h3>Vous pouvez remplacer cet aliment par</h3>
                <hr class="divider my-4" />
            </div>
        </div>
        <div class="container row">
            {% for instance in object_list %}

            <form class="justify-content-center text-center col-lg-4 col-sm-12 my-2"  id="search"  action="{% url 'account:save'  %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id_substitute" value="{{ instance.id }}">
                <input type="hidden" name="origin_id" value="{{ origin_product.id }}">

                <a class="align-content-center text-center my-col" href="{{ instance.get_absolute_url }}">
                    <img class="product-img" src="{{ instance.image_url }}">
                    <p class="">{{ instance.name }}</p>
                </a>

                <p class="x">{{ instance.nutri_score }}</p>

                <button class="btn btn-primary col-lg-12 col-md-12" type="submit">
                    <i class="far fa-save"></i>
                    Save
                </button>

            </form>

            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}